
[tool.vulture]
ignore_decorators = []
ignore_names = ["side_effect"]
make_whitelist = true
# 10 is very low, might need to adjust depending on circumstances
min_confidence = 10
paths = ["."]
sort_by_size = true